### PR TITLE
add keepalive to receive signals at all times.

### PR DESCRIPTION
**Pull request by martin-rueegg**
solves https://github.com/oetiker/znapzend/issues/168

in order to avoid an error message during shutdown, the following PR should be applied https://github.com/jberger/Mojo-IOLoop-ForkCall/pull/9.

### CODE REVIEW

**Comment by oetiker** [comment]
Your patch breaks at least the test suite ... as far as I understand, the reporter of #168 takes issue with the fact that znapzend does not abort the current zfs send operation ... or am I missing something ?

**Comment by martin-rueegg** [comment]
i don't know how my patch would break [`zfs recv`](https://travis-ci.org/oetiker/znapzend/jobs/111128736#L843) and [`zfs send`](https://travis-ci.org/oetiker/znapzend/jobs/111128736#L844).

is that really on a network connection? could there be an issue with the infrastructure? i don't think the worker threads should be blocked by the keepalive thread. that's the whole point about the threads, ain't it?
in order to test it here, could i send it to the same host using ssh? (i don't currently have an other host with a zfs filesystem)

**Comment by oetiker** [comment]
znapzend contains mock ssh and zfs commands ...

**Comment by martin-rueegg** [comment]
close due to https://github.com/oetiker/znapzend/pull/191#issuecomment-187680508

**Pull request closed without merging**
