### PR TITLE
Fix backup replication of inherited-config datasets

### PR DESCRIPTION
**Pull request by jimklimov**
Before this, they were trying to replicate into the original (parent) `dst_N` rather than into a properly shifted one.

### CODE REVIEW

**Comment by jimklimov** [comment]
Note: one failed line of coverage is for the case I am not sure we can hit in current reality, but handle for consistency just in case.

**Comment by jimklimov** [comment]
@oetiker : I think this one is good to merge :)

**Comment by oetiker** [comment]
if you request a review, then I know you think the PR is ready ... just click my name in the reviewer list.

**Comment by jimklimov** [comment]
As not a project member, I don't have a link to click in the Reviewers column ;) So have to CC in comments...

**Comment by jimklimov** [comment]
Seems good, no `not ok` and `done_` hits found in Travis build logs :)

**Comment by jimklimov** [comment]
The coverage fault is the same case as above, for displaying an error in the situation we don't really expect to happen IRL.

**Comment by jimklimov** [comment]
Green and covered (with the conditional-miss above), is there something more to fix here? :)

**Pull request merged**
