### PR TITLE
Fix trivial typos

### PR DESCRIPTION
**Pull request by chrisridd**
Just a bunch of typos in the docs.

### CODE REVIEW

**Comment by oetiker** [comment]
thanks!

**Comment by hadfl** [comment]
typos should be corrected in the source files since pods are generated your changes will be overwritten.

**Comment by chrisridd** [comment]
Well spotted @hadfl - I've just updated my branch with another commit: 6411eab912bad422cbcf363f10935ac904f650c2. The first commit is still relevant because it fixes the README.

Do you want another PR?

**Comment by hadfl** [comment]
yeah, please do another PR.

**Pull request merged**
