### PR TITLE
Autocreation fix

### PR DESCRIPTION
**Pull request by oetiker**

### CODE REVIEW

**Comment by oetiker** [comment]
I think that should take care of #206

**Comment by Wouter0100** [comment]
Hmm, let me test this PR :)

**Comment by gusioo** [comment]
Hi

I testing new znapzend from autocreation-fix branch but still cannot create missing dataset on destination.

Here is log from znapzend -d:

```
cannot open 'storage/dataset': dataset does not exist
# ssh -i /root/.ssh/id_rsa -p 40000 -o StrictHostKeyChecking=no -o batchMode=yes -o ConnectTimeout=30 user@192.168.251.192 zfs list -H -o name -t 'filesystem,volume' storage/dataset
cannot open 'storage/dataset': dataset does not exist
# zfs snapshot storage/dataset@autosnap_2016-05-05-132100
# ssh -i /root/.ssh/id_rsa -p 40000 -o StrictHostKeyChecking=no -o batchMode=yes -o ConnectTimeout=30 user@192.168.251.192 zfs list -H -o name -t 'filesystem,volume' storage/dataset
cannot open 'storage/dataset': dataset does not exist
# zfs list -H -o name -t snapshot -s creation -d 1 storage/dataset
```

Also in znapzend.log I got:

`[Thu May  5 13:06:01 2016] [warn] destination 'user@192.168.251.192:storage/dataset' does not exist or is offline. ignoring it for this round...`

Here is znapzend process with autoCreation switch:

`/usr/bin/perl /opt/znapzend/bin/znapzend --pidfile /var/run/znapzend.pid --logto /var/log/znapzend.log --daemonize --autoCreation --features=oracleMode`

**Comment by oetiker** [comment]
@gusioo thanks for testing ... updated my patch

**Comment by gusioo** [comment]
@oetiker thanks for update. Today I will check your patch and I let you know about results.

**Comment by gusioo** [comment]
@oetiker after compilation of new znapzend I got warnings:

```
[Fri May  6 10:20:02 2016] [warn] destination 'user@192.168.251.192:storage/dataset' does not exist or is offline. ignoring it for this round...
[Fri May  6 10:20:02 2016] [warn] Use of uninitialized value $_ in scalar chomp at /opt/znapzend/lib/ZnapZend/ZFS.pm line 159, <$snapshots> line 1.

[Fri May  6 10:20:02 2016] [warn] Use of uninitialized value $_ in scalar chomp at /opt/znapzend/lib/ZnapZend/ZFS.pm line 159, <$snapshots> line 2.

[Fri May  6 10:20:02 2016] [warn] Use of uninitialized value $_ in concatenation (.) or string at /opt/znapzend/lib/ZnapZend/ZFS.pm line 164, <$snapshots> line 2.

[Fri May  6 10:20:02 2016] [warn] Use of uninitialized value $_ in concatenation (.) or string at /opt/znapzend/lib/ZnapZend/ZFS.pm line 164, <$snapshots> line 2.

[Fri May  6 10:20:02 2016] [debug] cleaning up snapshots on storage/dataset
[Fri May  6 10:20:02 2016] [warn] Use of uninitialized value $ssh[2] in system at /opt/znapzend/lib/ZnapZend/ZFS.pm line 227.

[Fri May  6 10:20:02 2016] [warn] Use of uninitialized value $dataSet in concatenation (.) or string at /opt/znapzend/lib/ZnapZend/ZFS.pm line 227.

[Fri May  6 10:20:02 2016] [warn] Use of uninitialized value $ssh[2] in system at /opt/znapzend/lib/ZnapZend/ZFS.pm line 227.

[Fri May  6 10:20:02 2016] [warn] Use of uninitialized value $dataSet in concatenation (.) or string at /opt/znapzend/lib/ZnapZend/ZFS.pm line 227.

[Fri May  6 10:20:02 2016] [warn] ERROR: cannot destroy snapshot 
ERROR: cannot destroy snapshot 

```
Unfortunately still does not work.

**Comment by oetiker** [comment]
@gusioo another round of fixes is in in case you want to test :)

**Comment by gusioo** [comment]
@oetiker thanks I will test it :)

**Comment by gusioo** [comment]
@oetiker now it works! I tested remote sending and dataset on destination side was created.

Great job :+1: 

I think that you can merge this to master.

**Comment by oetiker** [comment]
yey finally

**Comment by gusioo** [comment]
As I said good job.

Now I can close my issue ;-)

**Pull request merged**
